env:
  browser: true
  commonjs: true
  es6: true
extends:
  - 'eslint:recommended'
  - plugin:import/errors
  - plugin:import/warnings
parser: babel-eslint
parserOptions:
  sourceType: module
  ecmaFeatures:
    jsx: true
plugins:
  - import
rules:
  indent:
    - error
    - 2
    - SwitchCase: 1
  quotes:
    - error
    - single
    - avoidEscape: true
      allowTemplateLiterals: true
  semi:
    - error
  curly:
    - error
    - all
  comma-dangle:
    - error
    - always-multiline
  comma-spacing:
    - error
    - before: false
      after: true
  block-spacing:
    - error
    - always
  array-bracket-spacing:
    - error
    - never
  object-curly-spacing:
    - error
    - always
  key-spacing:
    - error
    - beforeColon: false
      afterColon: true
      mode: strict
  space-before-function-paren:
    - error
    - never
  spaced-comment:
    - error
    - always
  space-in-parens:
    - error
    - never
  arrow-spacing:
    - error
    - before: true
      after: true
  no-multiple-empty-lines:
    - error
    - max: 2
      maxEOF: 1
      maxBOF: 0
  no-multi-spaces:
    - error
  space-infix-ops:
    - error
  no-undef:
    - off
  no-unused-vars:
    - off
  no-console:
    - off
